@startuml
skinparam shadowing false
skinparam responseMessageBelowArrow true
skinparam sequenceMessageAlign center
skinparam maxMessageSize 180
skinparam sequenceParticipant underline false
skinparam stereotypePosition top


actor "Cashier" as C
boundary "POS / Open shift UI" as UI <<boundary>>

== Open shift ==

C -> UI: enter opening cash, confirm
activate UI
UI -> UI: create local ShiftSession
UI --> C: enable sales
deactivate UI

@enduml
